apiVersion: v1
kind: Service
metadata:
  name: bingebox-mw-service
spec:
  type: NodePort
  selector:
    app: bingebox-mw
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
